//
//  DataCollector.swift collects data from JSON generated by backend web service and processes it
//  Database Read Example
//
//  Created by Ethan Peterson on 2017-03-06.
//  Copyright © 2017 Ethan Peterson. All rights reserved.
//

import Foundation

protocol dataModel : class {
    func itemsDownloaded(items: NSArray)
}

class DataCollector : NSObject, URLSessionDataDelegate {
    weak var delegate : dataModel!
    
    var data : NSMutableData = NSMutableData()
    
    let JSONLocation = "https://ethanpeterson.tech/service.php"
    
    func download() {
    }
}
