# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhatsTheDayiOS' do
 use_frameworks!
 pod 'Alamofire', '~> 4.3'
end
